version: '2'

services:
   db:
     image: mysql/mysql-server:5.7
     #command: --default-authentication-plugin=mysql_native_password
     command: --sql_mode=
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     env_file:
        - db.env       

    #dns:
    # restart: always
    # image: sameersbn/bind:9.11.3-20190706
    # environment:
    #    ISPCONFIG_HOST: ispconfig
    # ports:
    #  - "53:53/udp"
    #  - "53:53/tcp"
    #  - "10000:10000/tcp"
    #volumes:
    #- /docker-vol/bind:/data
    
   web:
     depends_on:
       - db
     build:
      context: web
      dockerfile: Dockerfile
     ports:
       - "8020:20"
       - "8021:21"
       - "8022:22"
       - "80:80"
       - "443:443"
       - "8080:8080"
     restart: always
     volumes:
       - web_ispconfig:/usr/local/ispconfig/
       - web_www:/var/www/
       - web_log:/var/log/
       - web_nginx_config:/etc/nginx
     env_file:
        - web.env

   mail:
     hostname: ${HOSTNAME}
     domainname: ${DOMAINNAME}
     depends_on:
       - db
     build:
      context: mail
      dockerfile: Dockerfile
     ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
     restart: always
     volumes:
      - mail_ispconfig:/usr/local/ispconfig/
      - mail_data:/var/mail
      - mail_state:/var/mail-state
      - mail_logs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
     env_file:
        - mail.env
        - mail/mailserver.env
     cap_add:
        - NET_ADMIN
        - SYS_PTRACE

volumes:
    db_data: {}
    web_www: {}
    web_log: {}
    web_nginx_config: {}
    web_ispconfig: {}
    mail_data: {}
    mail_state: {}
    mail_logs: {}
    mail_ispconfig: {}
